services:
  db:
    image: hub.hamdocker.ir/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: marzban_bot
      POSTGRES_PASSWORD: marzban_bot
      POSTGRES_DB: marzban_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
